name: native_edit_text
description: Native EditText.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.apexteam.native_edit_text
        pluginClass: NativeEditTextPlugin
      ios:
        pluginClass: NativeEditTextPlugin