# Use the parent analysis options settings and enable null-experiment.

include: ../analysis_options.yaml

analyzer:
  enable-experiment:
    - non-nullable
  errors:
    always_require_non_null_named_parameters: false # not needed with nnbd
    type_init_formals: false # https://github.com/dart-lang/linter/issues/2192
    unrelated_type_equality_checks: false # https://github.com/dart-lang/linter/issues/2196
    void_checks: false # https://github.com/dart-lang/linter/issues/2185
    unnecessary_null_comparison: false # https://github.com/dart-lang/language/issues/1018 , turned off until https://github.com/flutter/flutter/issues/61042
